-- MySQL Script generated by MySQL Workbench
-- Tue Jun  8 13:25:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Kardex_monitor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Kardex_monitor` ;

-- -----------------------------------------------------
-- Schema Kardex_monitor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Kardex_monitor` DEFAULT CHARACTER SET utf8 ;
USE `Kardex_monitor` ;

-- -----------------------------------------------------
-- Table `Kardex_monitor`.`ACT_Ingreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`ACT_Ingreso` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`ACT_Ingreso` (
  `id_ACt_ingreso` INT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `proveedor` VARCHAR(45) NOT NULL,
  `Documentos` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_ACt_ingreso`),
  UNIQUE INDEX `idtable1_UNIQUE` (`id_ACt_ingreso` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Kardex_monitor`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`Estado` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`Estado` (
  `idEstado` INT NOT NULL,
  `Nombre_estado` VARCHAR(45) NOT NULL,
  `Descripcion_estado` VARCHAR(224) NULL DEFAULT NULL,
  PRIMARY KEY (`idEstado`),
  UNIQUE INDEX `idEstado_UNIQUE` (`idEstado` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Kardex_monitor`.`Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`Marca` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`Marca` (
  `idMarca` INT NOT NULL,
  `Nombre_Marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`),
  UNIQUE INDEX `idMarca_UNIQUE` (`idMarca` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Kardex_monitor`.`Tipo_dispositivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`Tipo_dispositivo` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`Tipo_dispositivo` (
  `idTipo_dispositivo` INT NOT NULL,
  `Nombre_tip_dispo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_dispositivo`),
  UNIQUE INDEX `idTipo_dispositivo_UNIQUE` (`idTipo_dispositivo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Kardex_monitor`.`Modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`Modelo` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`Modelo` (
  `idModelo` INT NOT NULL,
  `Nombre_modelo` VARCHAR(45) NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  `Tipo_dispositivo_idTipo_dispositivo` INT NOT NULL,
  PRIMARY KEY (`idModelo`),
  UNIQUE INDEX `idModelo_UNIQUE` (`idModelo` ASC) VISIBLE,
  INDEX `fk_Modelo_Marca1_idx` (`Marca_idMarca` ASC) VISIBLE,
  INDEX `fk_Modelo_Tipo_dispositivo1_idx` (`Tipo_dispositivo_idTipo_dispositivo` ASC) VISIBLE,
  CONSTRAINT `fk_Modelo_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `Kardex_monitor`.`Marca` (`idMarca`),
  CONSTRAINT `fk_Modelo_Tipo_dispositivo1`
    FOREIGN KEY (`Tipo_dispositivo_idTipo_dispositivo`)
    REFERENCES `Kardex_monitor`.`Tipo_dispositivo` (`idTipo_dispositivo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Kardex_monitor`.`Regional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`Regional` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`Regional` (
  `Cod_Regional` INT NOT NULL,
  `Codigo_Sap` VARCHAR(45) NULL DEFAULT NULL,
  `Nombre_Regional` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Regional`),
  UNIQUE INDEX `idRegional_UNIQUE` (`Cod_Regional` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Kardex_monitor`.`Tiendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`Tiendas` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`Tiendas` (
  `Cod_Ncr` INT NOT NULL,
  `Nombre_Tienda` VARCHAR(45) NOT NULL,
  `Codigo_sap` VARCHAR(10) NOT NULL,
  `Ip_Server` VARCHAR(20) NOT NULL,
  `Ip_Pc` VARCHAR(20) NOT NULL,
  `Ip_Camaras` VARCHAR(45) NOT NULL,
  `Abierta` TINYINT NOT NULL,
  `Estado` VARCHAR(10) NOT NULL,
  `Regional_Cod_Regional` INT NOT NULL,
  PRIMARY KEY (`Cod_Ncr`),
  UNIQUE INDEX `Cod_Ncr_UNIQUE` (`Cod_Ncr` ASC) VISIBLE,
  INDEX `fk_Tiendas_Regional_idx` (`Regional_Cod_Regional` ASC) VISIBLE,
  CONSTRAINT `fk_Tiendas_Regional`
    FOREIGN KEY (`Regional_Cod_Regional`)
    REFERENCES `Kardex_monitor`.`Regional` (`Cod_Regional`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Kardex_monitor`.`Activo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`Activo` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`Activo` (
  `Serial` VARCHAR(95) NOT NULL,
  `ultima_modificacion` DATE NOT NULL,
  `observacion` VARCHAR(254) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  `ACT_Ingreso_id_ACt_ingreso` INT NOT NULL,
  `Modelo_idModelo` INT NOT NULL,
  `Ubicacionact_Cod_Ncr` INT NOT NULL,
  PRIMARY KEY (`Serial`),
  INDEX `fk_Activo_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  INDEX `fk_Activo_ACT_Ingreso1_idx` (`ACT_Ingreso_id_ACt_ingreso` ASC) VISIBLE,
  INDEX `fk_Activo_Modelo1_idx` (`Modelo_idModelo` ASC) VISIBLE,
  INDEX `fk_Activo_Tiendas1_idx` (`Ubicacionact_Cod_Ncr` ASC) VISIBLE,
  CONSTRAINT `fk_Activo_ACT_Ingreso1`
    FOREIGN KEY (`ACT_Ingreso_id_ACt_ingreso`)
    REFERENCES `Kardex_monitor`.`ACT_Ingreso` (`id_ACt_ingreso`),
  CONSTRAINT `fk_Activo_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `Kardex_monitor`.`Estado` (`idEstado`),
  CONSTRAINT `fk_Activo_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `Kardex_monitor`.`Modelo` (`idModelo`),
  CONSTRAINT `fk_Activo_Tiendas1`
    FOREIGN KEY (`Ubicacionact_Cod_Ncr`)
    REFERENCES `Kardex_monitor`.`Tiendas` (`Cod_Ncr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Kardex_monitor`.`Conf_pos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`Conf_pos` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`Conf_pos` (
  `idConf_pos` VARCHAR(40) NOT NULL,
  `IP_POS` VARCHAR(45) NOT NULL,
  `TIPO_POS` VARCHAR(45) NOT NULL,
  `Modelo_cpu` VARCHAR(45) NULL DEFAULT NULL,
  `Serial_Cpu` VARCHAR(45) NULL DEFAULT NULL,
  `Teclado` VARCHAR(45) NULL DEFAULT NULL,
  `Impresora` VARCHAR(45) NULL DEFAULT NULL,
  `Tiendas_Cod_Ncr` INT NOT NULL,
  PRIMARY KEY (`idConf_pos`),
  UNIQUE INDEX `idConf_pos_UNIQUE` (`idConf_pos` ASC) VISIBLE,
  INDEX `fk_Conf_pos_Tiendas1_idx` (`Tiendas_Cod_Ncr` ASC) VISIBLE,
  CONSTRAINT `fk_Conf_pos_Tiendas1`
    FOREIGN KEY (`Tiendas_Cod_Ncr`)
    REFERENCES `Kardex_monitor`.`Tiendas` (`Cod_Ncr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Kardex_monitor`.`Historial_Linia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`Historial_Linia` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`Historial_Linia` (
  `idHistorial_Linia` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL DEFAULT NULL,
  `Estado` VARCHAR(45) NULL DEFAULT NULL,
  `Tiendas_Cod_Ncr` INT NOT NULL,
  PRIMARY KEY (`idHistorial_Linia`),
  UNIQUE INDEX `idHistorial_Linia_UNIQUE` (`idHistorial_Linia` ASC) VISIBLE,
  INDEX `fk_Historial_Linia_Tiendas1_idx` (`Tiendas_Cod_Ncr` ASC) VISIBLE,
  CONSTRAINT `fk_Historial_Linia_Tiendas1`
    FOREIGN KEY (`Tiendas_Cod_Ncr`)
    REFERENCES `Kardex_monitor`.`Tiendas` (`Cod_Ncr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Kardex_monitor`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre_ingreso` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Kardex_monitor`.`Historial_act`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`Historial_act` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`Historial_act` (
  `idHistorial_act` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `tabla_modificada` VARCHAR(45) NOT NULL,
  `actividad_realizada` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Activo_Serial` VARCHAR(95) NOT NULL,
  PRIMARY KEY (`idHistorial_act`),
  UNIQUE INDEX `idHistorial_act_UNIQUE` (`idHistorial_act` ASC) VISIBLE,
  INDEX `fk_Historial_act_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Historial_act_Activo1_idx` (`Activo_Serial` ASC) VISIBLE,
  CONSTRAINT `fk_Historial_act_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Kardex_monitor`.`Usuario` (`idUsuario`),
  CONSTRAINT `fk_Historial_act_Activo1`
    FOREIGN KEY (`Activo_Serial`)
    REFERENCES `Kardex_monitor`.`Activo` (`Serial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Kardex_monitor`.`Servidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Kardex_monitor`.`Servidor` ;

CREATE TABLE IF NOT EXISTS `Kardex_monitor`.`Servidor` (
  `idServicios` INT NOT NULL,
  `POS_ARS` VARCHAR(45) NOT NULL DEFAULT 'NO ACTIVO',
  `FDS` VARCHAR(45) NOT NULL DEFAULT 'NO ACTIVO',
  `Postgres` VARCHAR(45) NOT NULL DEFAULT 'NO ACTIVO',
  `Wildfly` VARCHAR(45) NOT NULL DEFAULT 'NO ACTIVO',
  `ArsPluMnt` VARCHAR(45) NOT NULL DEFAULT 'NO ACTICO',
  `Tiendas_Cod_Ncr` INT NOT NULL,
  PRIMARY KEY (`idServicios`),
  UNIQUE INDEX `idServicios_UNIQUE` (`idServicios` ASC) VISIBLE,
  INDEX `fk_Servidor_Tiendas1_idx` (`Tiendas_Cod_Ncr` ASC) VISIBLE,
  CONSTRAINT `fk_Servidor_Tiendas1`
    FOREIGN KEY (`Tiendas_Cod_Ncr`)
    REFERENCES `Kardex_monitor`.`Tiendas` (`Cod_Ncr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `Kardex_monitor` ;

-- -----------------------------------------------------
-- procedure Listar_Modelo_marca_tp_dispo
-- -----------------------------------------------------

USE `Kardex_monitor`;
DROP procedure IF EXISTS `Kardex_monitor`.`Listar_Modelo_marca_tp_dispo`;

DELIMITER $$
USE `Kardex_monitor`$$
CREATE DEFINER=`bart`@`%` PROCEDURE `Listar_Modelo_marca_tp_dispo`()
BEGIN
SELECT idModelo,Nombre_modelo,idMarca,Nombre_Marca,idTipo_dispositivo,Nombre_tip_dispo FROM Kardex_monitor.Modelo 
inner join Kardex_monitor.Marca on 
Kardex_monitor.Modelo.Marca_idMarca =Kardex_monitor.Marca.idMarca
inner join Kardex_monitor.Tipo_dispositivo on
Kardex_monitor.Modelo.Tipo_dispositivo_idTipo_dispositivo= Kardex_monitor.Tipo_dispositivo.idTipo_dispositivo
;

END$$

DELIMITER ;


-- -----------------------------------------------------
-- procedure Listar_pos_info_tienda
-- -----------------------------------------------------

USE `Kardex_monitor`;
DROP procedure IF EXISTS `Kardex_monitor`.`Listar_pos_info_tienda`;

DELIMITER $$
USE `Kardex_monitor`$$
CREATE DEFINER=`bart`@`%` PROCEDURE `Listar_pos_info_tienda`()
BEGIN
SELECT * FROM Kardex_monitor.Conf_pos inner join Kardex_monitor.Tiendas on Kardex_monitor.Conf_pos.Tiendas_Cod_Ncr =Kardex_monitor.Tiendas.Cod_Ncr;
END$$







DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
